name: Build and Deploy
on: [pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test
        env:
          HEADLESS: true
          